holy_shiitake/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('recipes.urls'), name='recipes-urls'),
    path('accounts/', include('allauth.urls')),
]

HANDLER404 = 'holy_shiitake.views.custom_404_error'
HANDLER500 = 'holy_shiitake.views.custom_500_error'

recipes/urls.py
"""url paths"""
from django.urls import path
from . import views


urlpatterns = [
    path(
        '',
        views.RecipeList.as_view(),
        name='home'
    ),
    path(
        'recipes/all_recipes',
        views.AllRecipes.as_view(),
        name='all_recipes'
    ),
    path(
        'recipes/<slug:slug>/',
        views.RecipeView.as_view(),
        name='recipe_view'
    ),
    path(
        'recipes/<slug:slug>/moderate_recipe_view',
        views.ModerateRecipeView.as_view(),
        name='moderate_recipe_view'
    ),
    path(
        'like/<slug:slug>',
        views.RecipeLike.as_view(),
        name='recipe_like'
    ),
    path(
        'recipes/add',
        views.AddRecipe.as_view(),
        name="add_recipe"
    ),
    path(
        'recipes/my_recipes',
        views.UserRecipes.as_view(),
        name='user_recipes'
    ),
    path(
        'recipes/update_recipe/<slug:slug>',
        views.UpdateRecipe.as_view(),
        name='update_recipe'
    ),
    path(
        'recipes/<slug:slug>/delete_recipe/',
        views.DeleteRecipe.as_view(),
        name='delete_recipe'
    ),
    path(
        'search_results',
        views.search_results,
        name='search_results'
    ),
    path(
        'recipes/moderate_recipes',
        views.ModerateRecipes.as_view(),
        name='moderate_recipes'
    ),
    path(
        'recipes/<slug:slug>/approve_recipe',
        views.ApproveRecipe.as_view(),
        name='approve_recipe'
    ),
    path(
        'recipes/admin_update_recipe/<slug:slug>',
        views.ModerateUpdateRecipe.as_view(),
        name='moderate_update_recipe'
    ),
    path(
        'recipes/<slug:slug>/admin_delete_recipe/',
        views.ModerateDeleteRecipe.as_view(),
        name='moderate_delete_recipe'
    ),
]

recipes/models.py
"""MODELS"""

from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.utils.text import slugify


STATUS = ((0, "Draft"), (1, "Added"))


class Recipe(models.Model):
    """Recipe Model"""
    recipe_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="recipes"
    )
    added_on = models.DateTimeField(auto_now=True)
    updated_on = models.DateTimeField(auto_now=True)
    description = models.TextField()
    ingredients = models.TextField()
    method = models.TextField()
    recipe_image = CloudinaryField('image', default='placeholder')
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User,
        related_name="recipe_likes",
        blank=True
    )

    class Meta:
        ordering = ['-added_on']

    def __str__(self):
        return self.recipe_name

    def number_of_likes(self):
        return self.likes.count()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.recipe_name)
        super(Recipe, self).save(*args, **kwargs)


class Comment(models.Model):
    """Comments Model"""
    recipe = models.ForeignKey(
        Recipe,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    name = models.CharField(max_length=50)
    added_on = models.DateTimeField(auto_now=True)
    body = models.TextField()
    likes = models.ManyToManyField(
        User,
        related_name="comment_likes",
        blank=True
    )
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['added_on']

    def __str__(self):
        return f"Comment {self.body} by {self.name}"

    def number_of_likes(self):
        return self.likes.count()

recipes/forms.py
from .models import Comment, Recipe
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django.forms import HiddenInput


class CommentForm(forms.ModelForm):
    """Comment Form """
    class Meta:
        model = Comment
        fields = ('body',)


class RecipeForm(forms.ModelForm):
    """Recipe Form"""
    class Meta:
        model = Recipe
        fields = (
            'recipe_name',
            'description',
            'ingredients',
            'method',
            'recipe_image',
        )
        widgets = {
            'description': SummernoteWidget(),
            'ingredients': SummernoteWidget(),
            'method': SummernoteWidget(),
        }


class ApproveForm(forms.ModelForm):
    """Form to Approve Recipes"""
    class Meta:
        model = Recipe
        fields = (
            'slug',
            'status',
        )
        widgets = {
            'slug': HiddenInput(),
        }

recipes/views.py
""" Views """
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic, View
from django.views.generic.edit import UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.db.models import Q
from .models import Recipe
from .forms import CommentForm, RecipeForm, ApproveForm
from django.urls import reverse_lazy


class RecipeList(generic.ListView):
    """View to show a list of all recipes posted by all users"""
    model = Recipe
    queryset = Recipe.objects.filter(status=1).order_by('-added_on')[0:6]
    template_name = 'index.html'


class AllRecipes(generic.ListView):
    """View to show a list of all recipes posted by all users"""
    model = Recipe
    queryset = Recipe.objects.filter(status=1).order_by('recipe_name')
    template_name = 'all_recipes.html'
    paginate_by = 6


class RecipeView(View):
    """View to show recipe details for selected recipe"""
    def get(self, request, slug, *args, **kwargs):
        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by('added_on')
        liked = False
        if recipe.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(
            request,
            "recipe_view.html",
            {
                "recipe": recipe,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm()
            }
        )

    def post(self, request, slug, *args, **kwargs):
        queryset = Recipe.objects.filter(status=1)
        recipe = get_object_or_404(queryset, slug=slug)
        comments = recipe.comments.filter(approved=True).order_by('added_on')
        liked = False
        if recipe.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.save()
        else:
            comment_form = CommentForm()

        return render(
            request,
            "recipe_view.html",
            {
                "recipe": recipe,
                "comments": comments,
                "commented": True,
                "liked": liked,
                "comment_form": CommentForm()
            }
        )


class ModerateRecipeView(View):
    """View to show recipe details for selected recipe"""
    def get(self, request, slug, *args, **kwargs):
        queryset = Recipe.objects.filter(status=0)
        recipe = get_object_or_404(queryset, slug=slug)

        return render(
            request,
            "moderate_recipe_view.html",
            {
                "recipe": recipe,
            }
        )


class RecipeLike(View):
    """View to toggle like button"""
    def post(self, request, slug):
        recipe = get_object_or_404(Recipe, slug=slug)

        if recipe.likes.filter(id=request.user.id).exists():
            recipe.likes.remove(request.user)
        else:
            recipe.likes.add(request.user)

        return HttpResponseRedirect(reverse('recipe_view', args=[slug]))


class AddRecipe(View):
    """View to add a new recipe"""
    def get(self, request):
        context = {'form': RecipeForm()}
        return render(request, 'add_recipe.html', context)

    def post(self, request, *args, **kwargs):

        form = RecipeForm(request.POST, request.FILES)
        title = form.instance.recipe_name
        recipe_exists = Recipe.objects.filter(
            Q(recipe_name__iexact=title)
        ).exists()
        if recipe_exists:
            messages.error(
                request,
                'Recipe Name already exists, please choose another name'
            )
            context = {'form': form}
            return render(request, 'add_recipe.html', context)
        if form.is_valid():
            form.instance.author = self.request.user
            try:
                form.save()
                messages.success(request, "Your recipe is awaiting approval")
                return redirect('home')
            except:
                messages.error(request,
                               'Error: Only images can be uploaded.'
                               'Please try again.')
                context = {'form': form}
                return render(request, 'add_recipe.html', context)
        else:
            messages.error(request,
                           'Error: The form is not valid, '
                           'please check and try again')
            context = {'form': form}
            return render(request, 'add_recipe.html', context)


class UserRecipes(generic.ListView):
    """View to display recipes created by logged in user"""
    template_name = 'user_recipes.html'
    model = Recipe
    context_object_name = 'recipes'
    paginate_by = 6

    def get_queryset(self):
        return Recipe.objects.filter(
            author=self.request.user, status=1
        ).order_by('-added_on')


class UpdateRecipe(UpdateView):
    """View to update a recipe"""
    model = Recipe
    template_name = 'update_recipe.html'
    form_class = RecipeForm
    success_url = reverse_lazy('user_recipes')


class ModerateUpdateRecipe(UpdateView):
    """View to update a recipe"""
    model = Recipe
    template_name = 'update_recipe.html'
    form_class = RecipeForm
    success_url = reverse_lazy('moderate_recipes')


class DeleteRecipe(DeleteView):
    """View to delete recipe"""
    model = Recipe
    template_name = 'delete_recipe.html'
    success_url = reverse_lazy('user_recipes')


class ModerateDeleteRecipe(DeleteView):
    """View to delete recipe"""
    model = Recipe
    template_name = 'delete_recipe.html'
    success_url = reverse_lazy('moderate_recipes')


class ApproveRecipe(UpdateView):
    """View to toggle status of recipe from draft to approved"""
    model = Recipe
    template_name = 'approve_recipe.html'
    form_class = ApproveForm
    success_url = reverse_lazy('moderate_recipes')


# codemy.com YouTube tutorial for below search function
# https://www.youtube.com/watch?v=AGtae4L5BbI
# Create a Search Bar - Django
def search_results(request):
    """function to search recipes by title, description and ingredients"""
    if request.method == "GET":
        searched = request.GET['searched']
        recipes = Recipe.objects.distinct().filter(
            Q(recipe_name__icontains=searched) |
            Q(description__icontains=searched) |
            Q(ingredients__icontains=searched)
        )
        return render(request, 'search_results.html',
                      {'searched': searched, 'recipes': recipes})
    else:
        return render(request, 'search_results.html', {})


class ModerateRecipes(generic.ListView):
    """View to display draft recipes awaiting approval by admin"""
    template_name = 'moderate_recipes.html'
    model = Recipe
    context_object_name = 'recipes'
    paginate_by = 6

    def get_queryset(self):
        return Recipe.objects.filter(
            status=0
        ).order_by('-added_on')

templates/add_recipe.html
{% extends "base.html" %}

{% block content %}

{% load static %}

{% load crispy_forms_tags %}

<div class="container position-relative px-4 px-lg-5">
    <div class="row">
        <div class="col">
            <h1 class="h3 display-2 text-center title">Add A Recipe</h1>
            <form method="post" class="recipe-form" enctype='multipart/form-data'>
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="bt btn-success edit-button sub-btn text-white">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/all_recipes.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<!--PAGE HEADING-->
<div class="row">
    <div class="col-8 offset-2">
        <h3 class="h3 display-2 text-center title">All Recipes</h3>
        <hr>
    </div>
</div>

<!--MAIN CONTENT-->
<div class="container-fluid">
    <div class="row">
        <!--RECIPES-->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for recipe in recipe_list %}

                {% include 'includes/recipe_cards.html' with recipe=recipe %}
 
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

    <!--PAGE NAVIGATION-->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}" class="page-link">NEXT &raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

templates/approve_recipe.html
{% extends "base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<div class="container">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2">
            <h3>Approve {{ recipe.recipe_name }}</h3>
            <form method="post" action="">
                {% csrf_token %}
                <p>Are you sure you want to approve "{{ recipe.recipe_name }}"?  Approving this recipe will make it visible to all users.</p>
                {{ form | crispy }}
                <input type="submit" value="Confirm">
            </form>
        </div>
    </div>
</div>
        

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="A Recipe Sharing Site for delicious plant-based, vegan-friendly food."/>
    <meta name="keyword" content="plant-based, recipe, vegan, vegan-friendly, recipe-sharing, delicious food"/>
    <meta name="author" content="Shellie Downie"/>
    <title>HOLY SHIITAKE - Vegan Recipe Sharing Site</title>
    <!--FAVICON-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}" crossorigin="use-credentials">
    <!-- FONT AWESOME ICONS-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- BOOTSTRAP CSS LINK-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--CUSTOM CSS LINK-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
</head>

<body>
    <!--NAVIGATION BAR (included on every page)-->
    {% include 'nav.html' %}

    <!--ALERT MESSAGES-->
    {% if messages %}
    {% for message in messages %}

    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
        <p>{{ message }}</p>
        <button type="button" class="btn-close" aria-label="close" data-bs-dismiss="alert" id="closeAlert"></button>
    </div>

    {% endfor %}
    {% endif %}
    
    <!--MAIN CONTENT OF PAGE-->
    <main class="flex-shrink-0 main-bg">
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
    </main>

    <!--FOOTER (included on every page)-->
    {% include 'footer.html' %}


    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

templates/delete_recipe.html
{% extends "base.html" %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 mt-3 offset-md-2 center">
            <h3>Delete {{ recipe.recipe_name }}</h3>
            <form method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ recipe.recipe_name }}"?</p>
                <input type="submit" value="Confirm">
            </form>
        </div>
    </div>
</div>
        

{% endblock %}

templates/footer.html
<!--SOCIAL MEDIA LINKS-->
<footer>
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://facebook.com/" target="_blank" rel="'noopener"
                            aria-label="Visit our Facebook page (opens in a new tab)">
                            <span class="fa-stack fa-lg social-links grow">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-facebook fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://pinterest.com/" target="_blank" rel="'noopener"
                            aria-label="Find us on Pinterest (opens in a new tab)">
                            <span class="fa-stack fa-lg social-links grow">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-pinterest fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://instagram.com/" target="_blank" rel="'noopener"
                            aria-label="Check us out on Instagram (opens in a new tab">
                            <span class="fa-stack fa-lg social-links grow">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://youtube.com/" target="_blank" rel="'noopener"
                            aria-label="View our recipes on our Youtube Channel (opens in a new tab)">
                            <span class="fa-stack fa-lg social-links grow">
                                <i class="fas fa-circle fa-stack-2x"></i>
                                <i class="fab fa-youtube fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <div class="small text-center text-muted fst-italic">Created for Education Purposes 2022</div>
            </div>
        </div>
    </div>

</footer>

templates/index.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<!-- Page Header-->
<header>
<div id="main-image" class="container-fluid, image-container">
<div class="opaque-overlay">&nbsp;</div>
<div class="row text-on-top">
    <div class="col-12">
        <div class="text-center text-white header-text">
            <h1 class="text-center page-title">Holy Shiitake!</h1>
            <h2 class="slogan">- it's vegan?!</h2>
            <br>
            <div class="info-text">
                <p>Trying to eat less meat?  Eat more vegetables?  Or go completely meat and dairy free?</p>
                <p>Holy Shiitake! is brimming with delicious plant based recipes to help expand your culinary repertoire.</p>
                <p>Search the site or log in/sign up to add and share your own favourite vegan-friendly recipes!</p>

                {% if user.is_authenticated %}
                <!--Shows Add Recipe button if user is logged in-->
                <div>
                    <a class="btn btn-danger delete-button" href="{% url 'add_recipe' %}"
                    role="button">Add Recipe</a>
                </div>

                {% else %}
                <!--Shows Sign Up and Log In buttons if user is not logged in-->
                <div>
                  <a class="btn btn-success edit-button" href="{% url 'account_signup' %}"
                      role="button">Sign Up</a>
                  <a class="btn btn-danger delete-button" href="{% url 'account_login' %}"
                      role="button">Sign In</a>
                </div>
                {% endif %}
                
            </div>
        </div>
    </div>
</div>
</div>
</header>

<div class="row">
    <div class="col-8 offset-2">
        <h3 class="h3 display-2 text-center">Latest Recipes</h3>
        <hr>
    </div>
</div>

<!--Shows latest 6 recipes that have been added to site-->
<div class="container-fluid">
    <div class="row">
        <!-- Recipes -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for recipe in recipe_list %}

                {% include 'includes/recipe_cards.html' with recipe=recipe %}

                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/moderate_recipe_view.html
{% extends "base.html" %}

{% block content %}

{% load static %}

{% load crispy_forms_tags %}

<!-- Page Header-->
{% if "placeholder" in recipe.recipe_image.url %}
    <header class="masthead" style="background-image: url('{% static 'images/vegetables.webp' %}');">
{% else %}
    <header class="masthead" style="background-image: url('{{ recipe.recipe_image.url }}');">
 {% endif %}
        <div class="opaque-overlay">&nbsp;</div>
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="post-heading">
                        <h1>{{ recipe.recipe_name }}</h1>
                        <span class="meta">
                            Added by
                            {{ recipe.author }} | {{ recipe.added_on }}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Recipe Content-->
    <article class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <p>{{ recipe.description | safe }}</p>
                    <hr>
                    <h2>Ingredients</h2>
                    <p>{{ recipe.ingredients | safe}}</p>
                    <hr>
                    <h2>Method</h2>
                    <p>{{ recipe.method | safe }}</p>
                    <div class="row inline-block">
                        <div class="buttons">
                            <!-- APPROVE/EDIT/DELETE BUTTONS-->
                            <a class="btn btn-success approve-button" href="{% url 'approve_recipe' recipe.slug %}"
                                role="button">Approve</a>
                            <a class="btn btn-success edit-button" href="{% url 'moderate_update_recipe' recipe.slug %}"
                                role="button">Edit</a>
                            <a class="btn btn-danger delete-button"
                                href="{% url 'moderate_delete_recipe' recipe.slug %}" role="button">Delete</a>
                        </div>
                    </div>
                </div>
                </strong>
            </div>


        </div>
        </div>
        </div>
        </div>
    </article>

    {% endblock %}

templates/moderate_recipes.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<div class="row">
    <div class="col-8 offset-2">
        <h1 class="h3 display-2 text-center title">Moderate Recipes</h1>
        <hr>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <!-- Recipes -->
        {% if recipes %}
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for recipe in recipes %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in recipe.recipe_image.url %}
                                <img class="recipe-image card-img-top"
                                    src="https://res.cloudinary.com/bubblecloud/image/upload/v1653858415/vegetables_uwmym1.webp"
                                    alt="Heap of sliced vegetables">
                                {% else %}
                                <img class="recipe-image card-img-top" src="{{ recipe.recipe_image.url }}" height="300"
                                    alt="{{ recipe.recipe_name }}">
                                {% endif %}
                            </div>
                            <a href="{% url 'moderate_recipe_view' recipe.slug %}" class="recipe-link">
                                <h2 class="card-title">{{ recipe.recipe_name }}</h2>
                            </a>
                            <p class="card-text">{{ recipe.description |safe }}</p>
                            <hr>
                            <p class="card-text text-muted h6">{{ recipe.added_on }} <i class="far fa-heart"> </i>
                                {{ recipe.number_of_likes }}</p>

                            <!-- APPROVE/EDIT/DELETE BUTTONS-->
                            <a class="btn btn-success approve-button" href="{% url 'approve_recipe' recipe.slug %}"
                                role="button">Approve</a>
                            <a class="btn btn-success edit-button" href="{% url 'moderate_update_recipe' recipe.slug %}"
                                role="button">Edit</a>
                            <a class="btn btn-danger delete-button" href="{% url 'moderate_delete_recipe' recipe.slug %}"
                                role="button">Delete</a>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
        {% else %}
        <p class="center">There are no recipes awaiting approval.</p>
        {% endif %}
    </div>

    <!--PAGE NAVIGATION-->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}" class="page-link">NEXT &raquo;</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

templates/search_results.html
{% extends "base.html" %}

{% block content %}

<!--PAGE HEADING-->
<div class="row">
    <div class="col-8 offset-2">
        <h3 class="h3 display-2 text-center title">Search Results</h3>
        <hr>
    </div>
</div>

    {% if searched %}
        <h1 class="center">You searched for {{ searched }}</h1>
        <br>
        <div class="col-12 mt-3 left">
        <div class="row">
        {% if recipes %}
            {% for recipe in recipes %}

            {% include 'includes/recipe_cards.html' with recipe=recipe %}

                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
                </div>
            </div>
        {% else %}
        <p class="center">There are no recipes containing <strong>{{ searched }}</strong>.  Search for something else.</p>
        {% endif %}
    </div>
    
    {% else %}
        <p class="center message-to-user">Hey!! You forgot to search for a recipe!</p>
    {%endif %}

{% endblock %}

templates/update_recipe.html
{% extends "base.html" %}

{% block content %}

{% load static %}

{% load crispy_forms_tags %}

{% if user.is_authenticated and user.id == recipe.author.id or user.is_superuser %}

<div class="container position-relative px-4 px-lg-5">
    <div class="row">
        <div class="col">
            <h1>Edit Recipe</h1>
            <form method="POST" class="recipe-form">
                {% csrf_token %}
                {{ form | crispy }}
                <input type="submit" value="Update">
            </form>
        </div>
    </div>
</div>

{% endif %}

{% endblock %}